export * from './iAnimate'
export * from './iBase'
export * from './iDialog'
export * from './iDialogProps'
export * from './iList'
export * from './iListProps'
export * from './iSystem'
export * from './iSystemProps'
export * from './iTextProps'
export * from './iTouch'
export * from './iTouchProps'

export * from './iSketchAppProps'
export * from './iBaseStyles'
