const allPathIgnorePatterns = [
  '<rootDir>/bin/',
  '<rootDir>/generate/',
  '<rootDir>/.check/',
  '<rootDir>/.circleci/',
  '<rootDir>/.idea/',
  '<rootDir>/.next/',
  '<rootDir>/.vscode/',
  '<rootDir>/config/',
  '<rootDir>/coverage/',
  '<rootDir>/jest/',
  '<rootDir>/production-server/',
  '<rootDir>/production-cloud/',
  '<rootDir>/public/',
  '<rootDir>/static/',
  '<rootDir>/build/',
  '<rootDir>/dist/',
  '<rootDir>/styles/',
  '<rootDir>/node_modules/'
]

const transformIgnorePatternsArray = [
  'react-native',
  'react-sketchapp',
  'react-navigation',
  '@react-navigation',
  'static-container',
  'tcomb-form-native'
]

module.exports = {
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'babel-jest'
  },
  globals: {
    "CGSizeMake": true,
    "COSAlertWindow": true,
    "CGAffineTransformMakeRotation": true,
    "CGAffineTransformMakeScale": true,
    "CGAffineTransformMakeTranslation": true,
    "CGAffineTransformConcat": true,
    "log": true,
    "MSArtboardGroup": true,
    "MSColor": true,
    "MSImageData": true,
    "MSLayerGroup": true,
    "MSOvalShape": true,
    "MSRect": true,
    "MSRectangleShape": true,
    "MSShapeGroup": true,
    "MSTextLayer": true,
    "NSArray": true,
    "NSFontCondensedTrait": true,
    "NSFontItalicTrait": true,
    "NSFontManager": true,
    "NSFontSymbolicTrait": true,
    "NSFontTraitsAttribute": true,
    "NSFontWeightBlack": true,
    "NSFontWeightBold": true,
    "NSFontWeightHeavy": true,
    "NSFontWeightLight": true,
    "NSFontWeightMedium": true,
    "NSFontWeightRegular": true,
    "NSFontWeightSemibold": true,
    "NSFontWeightThin": true,
    "NSFontWeightTrait": true,
    "NSFontWeightUltraLight": true,
    "NSFont": true,
    "NSFontAttributeName": true,
    "NSImage": true,
    "NSKernAttributeName": true,
    "NSMakeRect": true,
    "NSMutableParagraphStyle": true,
    "NSParagraphStyleAttributeName": true,
    "NSString": true,
    "NSStringDrawingUsesLineFragmentOrigin": true,
    "NSTextField": true,
    "NSTextView": true,
    "NSURL": true,
    "NSView": true,
    "NSMutableAttributedString": true,
    "React$Component": true,
    "React$Element": true,
    "ReactClass": true,
    "ReactComponent": true,
    "context": true
  },
  moduleFileExtensions: [
    'ts',
    'tsx',
    'js',
    'jsx',
    'json',
    'ios.ts',
    'ios.tsx',
    'android.ts',
    'android,.tsx'
  ],
  testMatch: ['**/*.test.ts?(x)'],
  moduleNameMapper: {
    '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'identity-obj-proxy',
  },
  testPathIgnorePatterns: allPathIgnorePatterns,
  transformIgnorePatterns: [`node_modules/(?!(jest-)?${transformIgnorePatternsArray.join('|')})`],
  collectCoverage: true,
  coveragePathIgnorePatterns: allPathIgnorePatterns
}
